name: KaleidoscopeCookeryPlugin
version: '${version}'
main: net.kaleidoscope.cookery.plugin.KaleidoscopeCookeryPlugin
api-version: '1.21'
folia-supported: true

dependencies:
  server:
    CraftEngine:
      load: BEFORE
      required: true
    PlaceholderAPI:
      load: BEFORE
      required: false
