name: KaleidoscopeCookeryPlugin
version: '${version}'
main: net.kaleidoscope.cookery.plugin.KaleidoscopeCookeryPlugin
api-version: '1.21'

dependencies:
  server:
    CraftEngine:
      load: BEFORE
      required: true
